name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]
        directory: ['./amplify/backend/function/checkingUrl/', ./App.test.js]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        # working-directory: ${{ matrix.directory }}
        run: |
          npm install
      - name: Run tests
        working-directory: ${{ matrix.directory }}
        run: |
          npm test
